### ISSUE TITLE
2048 default memory pukes on st2 pack install kubernetes

### ISSUE THREAD

**Issue by lakshmi-kannan** [StackStorm/st2vagrant#26]
To repro: 
```
vagrant up st2
st2 pack install kubernetes
```

This pretty much hung and crashed rabbit and mongo. I accidentally noticed that things like ps auxww | grep didn't work.

```
ubuntu@st2vagrant:~$ ps auxww | grep rabbit
-bash: fork: Cannot allocate memory
ubuntu@st2vagrant:~$
```

Then I bumped the mem limit to 4096 and ran exact commands and watched htop take up 1.8GB of RAM. It's the kubernetes pack's dep running gcc to compile native extensions and running all the sensors in one go I believe. 

This took a customer and I like 2 hours to figure out the root cause. We would be better off recommending 4G.

**Comment by estee-tew** [comment]
https://stackstorm.slack.com/archives/community/p1491857452578929
