### ISSUE TITLE
Allow choice of provisioning method

### ISSUE THREAD

**Issue by cognifloyd** [StackStorm/st2vagrant#30]
It would be nice to be able to use ansible-st2 instead of the install script to provision the box.

**Comment by armab** [comment]
There are already Vagrantfile in `ansible-st2` repo itself, which I believe does the same thing, see: https://github.com/StackStorm/ansible-st2/blob/master/Vagrantfile

**Comment by cognifloyd** [comment]
Ah. Of course! How did I miss that?

Maybe a note in the st2vagrant readme pointing out alternative vagrant boxes with other installation methods would be nice.

- StackStorm/ansible-st2 has a Vagrantfile
- StackStorm/chef-stackstorm has a vagrantfile
- StackStorm/puppet-st2 does not have a Vagrantfile
- StackStorm/docker-st2 does not have a Vagrantfile (and should not unless you wanted to build a docker host with it).
- StackStorm/bwcvagrant is st2vagrant, but with bwc
