### ISSUE TITLE
Image could have libkrb5-dev / devel-libkrb5 pre installed for ansible pack

### ISSUE THREAD

**Issue by tonybaloney** [StackStorm/st2vagrant#31]
To save people tripping over that ansible pack installation issue, suggest adding the ansible pack system pre-reqs to this image.

See https://stackstorm-community.slack.com/archives/C066APT88/p1545229655200400 for a full, detailed bug report by user

**Comment by armab** [comment]
This will make `Ansible` pack "special" which is not true.
We have more packs in StackStorm Exchange that require OS-level dependencies. If we install Ansible OS-level dependency, then should follow the same for others.

I don't think it's a good idea, but instead this issue bumps improving the experience in st2 itself. Example is defining on pack level libs/binaries requirements and showing a better error-message if they absent. I think though we can't install them automatically on user's system as pack dependency.


----

Additionally, the correct repo for that specific Slack community story is different.
Official pre-built "demo" Vagrant Cloud box which is highlighted in Installation docs: https://docs.stackstorm.com/install/vagrant.html has source code located at https://github.com/StackStorm/packer-st2
