### ISSUE TITLE
Require Minimum Vagrant Version

### ISSUE THREAD

**Issue by punkrokk** [StackStorm/st2vagrant#38]
Seems reasonable to require the latest, or at least 2.0+
https://www.vagrantup.com/docs/vagrantfile/vagrant_version.html

```Vagrant.require_version ">= 2.2.0"```

or

```Vagrant.require_version ">= 2.2.4"```

**Comment by LindsayHill** [comment]
Agreed, seems reasonable. `>=2.2.0` sounds like a good choice.
