### ISSUE TITLE
guest machine entered an invalid state while waiting for it to boot

### ISSUE THREAD

**Issue by punalpatel** [StackStorm/st2vagrant#4]
st2vagrant# vagrant up
Bringing machine 'st2' up with 'virtualbox' provider...
==> st2: Importing base box 'bento/ubuntu-14.04'...
==> st2: Matching MAC address for NAT networking...
==> st2: Checking if box 'bento/ubuntu-14.04' is up to date...
==> st2: Setting the name of the VM: st2vagrant
==> st2: Clearing any previously set network interfaces...
==> st2: Preparing network interfaces based on configuration...
    st2: Adapter 1: nat
    st2: Adapter 2: hostonly
==> st2: Forwarding ports...
    st2: 22 (guest) => 2222 (host) (adapter 1)
==> st2: Running 'pre-boot' VM customizations...
==> st2: Booting VM...
==> st2: Waiting for machine to boot. This may take a few minutes...
    st2: SSH address: 127.0.0.1:2222
    st2: SSH username: vagrant
    st2: SSH auth method: private key
The guest machine entered an invalid state while waiting for it
to boot. Valid states are 'starting, running'. The machine is in the
'gurumeditation' state. Please verify everything is configured
properly and try again.

If the provider you're using has a GUI that comes with it,
it is often helpful to open that and watch the machine, since the
GUI often has more helpful error messages than Vagrant can retrieve.
For example, if you're using VirtualBox, run `vagrant up` while the
VirtualBox GUI is open.

The primary issue for this error is that the provider you're using
is not properly configured. This is very rarely a Vagrant issue.
st2vagrant#

**Comment by manasdk** [comment]
`gurumeditation` is usually a memory issue  as per https://forums.virtualbox.org/viewtopic.php?f=1&t=18965
